/* main_example.c
 * Example integration of the STM32 Self-Diagnostic skeleton into a CubeMX project.
 * Copy this into your project's Src/ folder and adapt the includes and HAL transmit call.
 */

#include "diag.h"
#include <string.h>

// Include HAL headers for UART if you want to forward output via UART
// #include "usart.h" // generated by CubeMX

// Provide diag_output by forwarding to your UART or LCD. The function is weak in diag.c
// so you can either implement it here or in a separate file.

// Example using HAL_UART_Transmit (uncomment and adapt if using HAL):
/*
void diag_output(const char *msg) {
    if (msg == NULL) return;
    HAL_UART_Transmit(&huart1, (uint8_t*)msg, strlen(msg), 200);
}
*/

// Fallback if HAL not present: use a minimal implementation that does nothing
void diag_output(const char *msg) {
    (void)msg;
}

int main(void) {
    // Standard CubeMX initialization here
    // HAL_Init(); SystemClock_Config(); MX_GPIO_Init(); MX_USART1_UART_Init(); MX_FREERTOS_Init();

    // Start diagnostics and intro
    diag_start_tasks();

    // Start scheduler (if using FreeRTOS)
#ifdef FREERTOS_PRESENT
    vTaskStartScheduler();
#endif

    // If no RTOS, loop forever
    while (1) {
        // If diag_start_tasks ran inline (no FreeRTOS), just idle here or reset after delay.
    }

    return 0;
}
