import os
import subprocess
import sys
import tkinter as tk
from tkinter import messagebox, ttk

try:
    from diary_core import DiaryEngine
except Exception:  # pragma: no cover - fallback for standalone use
    class DiaryEngine:
        def __init__(self, storage_path=None):
            self.storage_path = storage_path or os.path.join(
                os.path.dirname(os.path.abspath(__file__)), "diary_entries.txt"
            )
            os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)

        def write_entry(self, text: str):
            with open(self.storage_path, "a", encoding="utf-8") as handle:
                handle.write(text + "\n")

        def auto_entry(self):
            self.write_entry("[AUTO] Diary entry generated by upgrade console")


def resolve_repo_target(repo_target, fallback_path):
    candidate = (repo_target or "").strip()
    if candidate:
        return os.path.abspath(candidate)
    return os.path.abspath(fallback_path)


def build_git_command(args):
    if not args:
        return ["git"]
    if args[0].lower() == "git":
        return list(args)
    return ["git", *args]


def run_git_command(args, cwd=None):
    command = build_git_command(args)
    return subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False)


def should_use_terminal_mode(force_terminal=False, environment=None):
    if force_terminal:
        return True
    env = environment or os.environ
    if os.name == "nt":
        return True
    return not env.get("DISPLAY") and not env.get("WAYLAND_DISPLAY")


def clone_repository(repo_url, target_dir=None):
    if not repo_url or not repo_url.strip():
        raise ValueError("A repository URL is required.")

    target_dir = resolve_repo_target(target_dir, os.path.join(os.getcwd(), "cloned_repo"))
    if os.path.exists(target_dir) and os.listdir(target_dir):
        raise FileExistsError(
            f"Target directory already exists and is not empty: {target_dir}"
        )

    result = run_git_command(["clone", repo_url.strip(), target_dir], cwd=os.getcwd())
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "Git clone failed.")
    return result


def update_repository(target_dir=None, remote="origin", branch=None):
    target_dir = resolve_repo_target(target_dir, os.path.dirname(os.path.abspath(__file__)))
    git_dir = os.path.join(target_dir, ".git")
    if not os.path.isdir(git_dir):
        raise FileNotFoundError(f"No git repository found at {target_dir}")

    args = ["-C", target_dir, "pull", "--ff-only", remote]
    if branch:
        args.extend([branch])

    result = run_git_command(args, cwd=target_dir)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "Git pull failed.")
    return result


class UpgradeConsole(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Nubian Upgrade Console")
        self.geometry("940x660")
        self.diary = DiaryEngine()
        self._build_ui()

    def _build_ui(self):
        banner = tk.Label(
            self,
            text="GENIUS THREE-DIMENSIONAL BATTLE CHESS – NUBIAN SPACECRAFT EDITION",
            font=("Segoe UI", 12, "bold"),
            bg="#101020",
            fg="#f0f0ff",
            pady=10,
        )
        banner.pack(fill="x")

        notebook = ttk.Notebook(self)
        notebook.pack(fill="both", expand=True, padx=10, pady=10)

        diary_frame = ttk.Frame(notebook)
        notebook.add(diary_frame, text="Diary Core")
        self._build_diary_tab(diary_frame)

        upgrade_frame = ttk.Frame(notebook)
        notebook.add(upgrade_frame, text="Upgrade Class")
        self._build_upgrade_tab(upgrade_frame)

        git_frame = ttk.Frame(notebook)
        notebook.add(git_frame, text="Clone & Update")
        self._build_git_tab(git_frame)

        chess_frame = ttk.Frame(notebook)
        notebook.add(chess_frame, text="3D Battle Chess")
        self._build_chess_tab(chess_frame)

    def _build_diary_tab(self, parent):
        entry_label = ttk.Label(parent, text="Manual Entry:")
        entry_label.pack(anchor="w", pady=(10, 0))

        self.entry_text = tk.Text(parent, height=6)
        self.entry_text.pack(fill="x", pady=5)

        btn_frame = ttk.Frame(parent)
        btn_frame.pack(fill="x", pady=5)

        write_btn = ttk.Button(btn_frame, text="Write to Diary", command=self.write_to_diary)
        write_btn.pack(side="left", padx=5)

        auto_btn = ttk.Button(btn_frame, text="Trigger Auto Entry", command=self.auto_entry)
        auto_btn.pack(side="left", padx=5)

    def write_to_diary(self):
        text = self.entry_text.get("1.0", "end").strip()
        if not text:
            messagebox.showwarning("Empty", "No text to write.")
            return
        self.diary.write_entry(text)
        messagebox.showinfo("Saved", "Entry written to diary.")
        self.entry_text.delete("1.0", "end")

    def auto_entry(self):
        self.diary.auto_entry()
        messagebox.showinfo("Auto", "Autonomous entry added.")

    def _build_upgrade_tab(self, parent):
        desc = ttk.Label(
            parent,
            text="Define and apply upgrades to the diary engine.\n"
            "Think of these as new behaviours or modifiers.",
            justify="left",
        )
        desc.pack(anchor="w", pady=(10, 5))

        self.spacecraft_mode = tk.BooleanVar(value=False)

        spacecraft_check = ttk.Checkbutton(
            parent,
            text="Enable Nubian Spacecraft Mode (prefix entries with starship log)",
            variable=self.spacecraft_mode,
            command=self.apply_spacecraft_mode,
        )
        spacecraft_check.pack(anchor="w", pady=5)

        self.auto_tag_var = tk.StringVar(value="[GENIUS-CHESS]")
        tag_frame = ttk.Frame(parent)
        tag_frame.pack(fill="x", pady=10)

        ttk.Label(tag_frame, text="Auto-tag prefix:").pack(side="left")
        ttk.Entry(tag_frame, textvariable=self.auto_tag_var, width=20).pack(side="left", padx=5)
        ttk.Button(tag_frame, text="Apply Auto-Tag Upgrade", command=self.apply_auto_tag).pack(
            side="left", padx=5
        )

    def apply_spacecraft_mode(self):
        original_write = self.diary.write_entry

        if self.spacecraft_mode.get():
            def spacecraft_write(text: str):
                prefix = "[NUBIAN STARSHIP LOG] "
                original_write(prefix + text)

            self.diary.write_entry = spacecraft_write
            messagebox.showinfo("Upgrade Applied", "Nubian Spacecraft Mode enabled.")
        else:
            self.diary = DiaryEngine(self.diary.storage_path)
            messagebox.showinfo("Upgrade Removed", "Nubian Spacecraft Mode disabled.")

    def apply_auto_tag(self):
        tag = self.auto_tag_var.get().strip()
        if not tag:
            messagebox.showwarning("No Tag", "Provide a tag prefix.")
            return

        original_write = self.diary.write_entry

        def tagged_write(text: str):
            original_write(f"{tag} {text}")

        self.diary.write_entry = tagged_write
        messagebox.showinfo("Upgrade Applied", f"Auto-tagging enabled with prefix: {tag}")

    def _build_git_tab(self, parent):
        ttk.Label(parent, text="Repository URL:").pack(anchor="w", pady=(10, 0))
        self.repo_url_var = tk.StringVar(value="")
        ttk.Entry(parent, textvariable=self.repo_url_var, width=70).pack(fill="x", pady=5)

        ttk.Label(parent, text="Target directory:").pack(anchor="w", pady=(8, 0))
        self.repo_target_var = tk.StringVar(value=os.path.abspath(os.path.dirname(__file__)))
        ttk.Entry(parent, textvariable=self.repo_target_var, width=70).pack(fill="x", pady=5)

        button_frame = ttk.Frame(parent)
        button_frame.pack(fill="x", pady=10)
        ttk.Button(button_frame, text="Clone Repository", command=self.clone_repository_action).pack(
            side="left", padx=5
        )
        ttk.Button(button_frame, text="Update This Repository", command=self.update_repository_action).pack(
            side="left", padx=5
        )

        self.git_status_var = tk.StringVar(value="Ready to clone or update.")
        ttk.Label(parent, textvariable=self.git_status_var, wraplength=700, justify="left").pack(
            anchor="w", pady=(8, 0)
        )

    def clone_repository_action(self):
        repo_url = self.repo_url_var.get().strip()
        target_dir = self.repo_target_var.get().strip()

        if not repo_url:
            messagebox.showwarning("Missing URL", "Please enter a repository URL.")
            return

        try:
            result = clone_repository(repo_url, target_dir)
            self.git_status_var.set(f"Clone completed. {result.stdout.strip() or result.stderr.strip()}")
            messagebox.showinfo("Clone complete", "Repository cloned successfully.")
        except Exception as exc:  # pragma: no cover - UI path
            self.git_status_var.set(f"Clone failed: {exc}")
            messagebox.showerror("Clone failed", str(exc))

    def update_repository_action(self):
        target_dir = self.repo_target_var.get().strip()
        try:
            result = update_repository(target_dir)
            self.git_status_var.set(f"Update completed. {result.stdout.strip() or result.stderr.strip()}")
            messagebox.showinfo("Update complete", "Repository updated successfully.")
        except Exception as exc:  # pragma: no cover - UI path
            self.git_status_var.set(f"Update failed: {exc}")
            messagebox.showerror("Update failed", str(exc))

    def _build_chess_tab(self, parent):
        info = ttk.Label(
            parent,
            text=(
                "Here lives the future: GENIUS 3D Battle Chess aboard a Nubian spacecraft.\n"
                "For now, this tab is a stub where you can later embed a Pygame/OpenGL window\n"
                "or a custom engine that visualises moves and ties them to diary events."
            ),
            justify="left",
        )
        info.pack(anchor="w", pady=10)

        ttk.Button(parent, text="Log Chess Move to Diary", command=self.log_chess_move).pack(
            anchor="w", pady=5
        )

    def log_chess_move(self):
        self.diary.write_entry("[CHESS] Nubian starship: 3D move executed on battle board.")
        messagebox.showinfo("Logged", "Chess move logged to diary.")


if __name__ == "__main__":
    if should_use_terminal_mode(force_terminal=False):
        print("Upgrade console running in terminal mode. Use the Clone & Update tab workflow from the GUI when available.")
        print("Repository helpers are available via the Python module API.")
    else:
        app = UpgradeConsole()
        app.mainloop()
